"""冻结的 V2-4 情景阈值；修改必须升级 policy_version 并重做验证。"""
DIRECTIONAL_MARGIN=.10
RANGE_MARGIN=.05
NEWS_DELTA_THRESHOLD=.15
DEFAULT_SHOCK_FLOOR=.03
ATR_SHOCK_MULTIPLIER=2.0
INTRADAY_QUOTE_MAX_AGE_MINUTES=15
PRE_QUOTE_MAX_AGE_MINUTES=45
QUOTE_FUTURE_TOLERANCE_MINUTES=5
POLICY_VERSION="scenario_policy_v1"
US_PRE_QUOTE_SOURCES=frozenset({"nasdaq", "nasdaq.com", "yfinance"})
INTRADAY_QUOTE_SOURCES=frozenset({"tickflow"})
