"""V2-11 注入式边界：页面只依赖读取、时钟、任务和导出能力。"""
from __future__ import annotations
from typing import Protocol
from tradehelper_v2.contracts import HistoricalEvaluationQuery, ReportDocument, ReportHistoryQuery

class PresentationReadPort(Protocol):
    def list_report_history(self, query: ReportHistoryQuery): ...
    def get_report_document(self, report_id: str) -> ReportDocument|None: ...
class EvaluationReadPort(Protocol):
    def build(self, query: HistoricalEvaluationQuery, *, outcomes=(), metrics=(), built_at): ...
class ExportPort(Protocol):
    def __call__(self, document: ReportDocument, *, format): ...
class ClockPort(Protocol):
    def __call__(self): ...
